dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.0

  # HTTP requests
  http: ^0.13.6

  # Color picker UI
  flutter_colorpicker: ^1.1.0

  # (optional) material icons, etc. are included with flutter SDK
