dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.0

  # HTTP requests
  http: ^0.13.6

  # Color picker UI
  flutter_colorpicker: ^1.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Packages for automatic TypeAdapter generation
  hive_generator: ^2.0.1 # Use the latest version
  build_runner: ^2.4.6 # Use the latest version
